# Generated by Django 5.1 on 2024-08-14 12:30

import property_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0002_rename_description_property_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to=property_app.models.get_image_path),
        ),
    ]
