# Generated by Django 5.1 on 2024-08-15 04:24

import property_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=property_app.models.get_image_path),
        ),
    ]
