# Generated by Django 5.1 on 2024-08-15 09:41

import property_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=property_app.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='property_app.amenity'),
        ),
        migrations.AlterField(
            model_name='property',
            name='locations',
            field=models.ManyToManyField(blank=True, to='property_app.location'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rating',
            field=models.TextField(blank=True, null=True),
        ),
    ]
