# Generated by Django 5.1 on 2024-08-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0005_alter_image_image_alter_location_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
