# Generated by Django 5.1 on 2024-08-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0006_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
